#mybatis-plus
mybatis-plus:
   mapper-locations: com/banxue/*/mapper/xml/*.xml
   type-aliases-package: com.banxue.*.entity
spring:
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
   mvc:
        static-path-pattern: /**
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      cache: false
   profiles:
      active: dev
# server
server:
    port: 8084
data:
   name: 21
   
# 打印sql
logging:
  level:
     com.banxue.projects.mapper : debug
